Repository ansible-community/molecule-libvirt, pull requests merged in 2021-05, with the labels that each got.

#16 Make Zuul CI a 3rd party one
  bindep.txt
  zuul.d/layout.yaml
Labels: skip-changelog

#19 VMs can be deployed on local and remote hosts that have a bridge.
  README.rst
  molecule_libvirt/cookiecutter/scenario/driver/libvirt/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  molecule_libvirt/cookiecutter/scenario/driver/libvirt/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule_libvirt/cookiecutter/scenario/driver/libvirt/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule_libvirt/playbooks/create.yml
  molecule_libvirt/playbooks/destroy.yml
  molecule_libvirt/playbooks/templates/meta-data.j2
  molecule_libvirt/playbooks/templates/network/network.xml.j2
  molecule_libvirt/playbooks/templates/user-data.j2
  molecule_libvirt/playbooks/templates/vm/vm.xml.j2
  setup.cfg
  test_requirements.yml
Labels: enhancement, feature

#25 Fix umask of the vm image
  molecule_libvirt/playbooks/create.yml
Labels: bug

#23 Add code owners
  .github/CODEOWNERS
Labels: skip-changelog

#27 Fix/cpu in template
  README.rst
  molecule_libvirt/playbooks/templates/vm/vm.xml.j2
Labels: bug
