Repository ansible-community/molecule-libvirt, pull requests merged in 2021-12, with the labels that each got.

#36 Remove ceiling from project dependencies
  setup.cfg
Labels: bug

#37 Adopt reusable GHA workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#39 Fixed missing item.
  molecule_libvirt/playbooks/create.yml
  molecule_libvirt/playbooks/templates/vm/vm.xml.j2
Labels: enhancement
